stages:
  - search
  - fetch_resources
  - consolidate

variables:
  INSTANCE_NAME: "${INSTANCE_NAME}"  # Input: instance name to search for

# Before each job, create temp directories for logs and data
before_script:
  - mkdir -p /tmp/output

# Search for instances in all namespaces and services for EDCR PROD ACTIVE
search_edcr_prod:
  stage: search
  parallel:
    matrix:
      - SERVICE: "cache-prod"
      - SERVICE: "cache-prod-local-mode"
      - SERVICE: "cache-utility"
      - SERVICE: "tp2-cache-prod-a"
      - SERVICE: "tp2-cache-prod-b"
  script:
    - echo "Searching for instance $INSTANCE_NAME in namespace $SERVICE..."
    - export NAMESPACE=$SERVICE
    - NAMESPACE_FOUND=$(kubectl get pods --namespace $NAMESPACE -o wide | grep "$INSTANCE_NAME")
    - if [ -n "$NAMESPACE_FOUND" ]; then
        echo "Instance found in namespace $NAMESPACE";
        echo "$NAMESPACE, $INSTANCE_NAME" >> /tmp/output/edcr_instances.txt;
      else
        echo "Instance not found in namespace $NAMESPACE";
      fi;
  tags:
    - cache-utility-edcr
    - cache-edcr-local-mode
    - tp2-edcr-prod-a
    - tp2-edcr-prod-b

# Search for instances in all namespaces and services for EDCO TEST
search_edco_test:
  stage: search
  parallel:
    matrix:
      - SERVICE: "cache-prep-local-mode"
      - SERVICE: "cache-prep"
      - SERVICE: "cache-test"
      - SERVICE: "tp2-edco-cache-test-b"
      - SERVICE: "tp2-edco-cache-test-c"
  script:
    - echo "Searching for instance $INSTANCE_NAME in namespace $SERVICE..."
    - export NAMESPACE=$SERVICE
    - NAMESPACE_FOUND=$(kubectl get pods --namespace $NAMESPACE -o wide | grep "$INSTANCE_NAME")
    - if [ -n "$NAMESPACE_FOUND" ]; then
        echo "Instance found in namespace $NAMESPACE";
        echo "$NAMESPACE, $INSTANCE_NAME" >> /tmp/output/edco_test_instances.txt;
      else
        echo "Instance not found in namespace $NAMESPACE";
      fi;
  tags:
    - cache-utility-test
    - cache-test-local-mode
    - tp2-edco-cache-test-b
    - tp2-edco-cache-test-c

# Fetch resource data from EDCR PROD ACTIVE namespaces
fetch_resources_edcr:
  stage: fetch_resources
  needs: ["search_edcr_prod"]
  parallel:
    matrix:
      - SERVICE: "cache-prod"
      - SERVICE: "cache-prod-local-mode"
      - SERVICE: "tp2-cache-prod-a"
      - SERVICE: "tp2-cache-prod-b"
  script:
    - |
      fetch_resource_data() {
        NAMESPACE=$SERVICE
        export NAMESPACE
        STS_NAME=$(kubectl get statefulsets --namespace $NAMESPACE | grep "$INSTANCE_NAME" | awk '{print $1}')
        if [ -n "$STS_NAME" ]; then
          echo "Fetching resources for $STS_NAME in namespace $NAMESPACE..."
          kubectl get statefulset $STS_NAME --namespace $NAMESPACE -o json | jq '.spec.template.spec.containers[] | {resources}' > /tmp/output/resources_$NAMESPACE.json
        fi
      }
      fetch_resource_data
  tags:
    - cache-utility-edcr
    - cache-edcr-local-mode
    - tp2-edcr-prod-a
    - tp2-edcr-prod-b

# Fetch resource data from EDCO TEST namespaces
fetch_resources_edco:
  stage: fetch_resources
  needs: ["search_edco_test"]
  parallel:
    matrix:
      - SERVICE: "cache-prep"
      - SERVICE: "cache-test"
      - SERVICE: "tp2-edco-cache-test-b"
      - SERVICE: "tp2-edco-cache-test-c"
  script:
    - |
      fetch_resource_data() {
        NAMESPACE=$SERVICE
        export NAMESPACE
        STS_NAME=$(kubectl get statefulsets --namespace $NAMESPACE | grep "$INSTANCE_NAME" | awk '{print $1}')
        if [ -n "$STS_NAME" ]; then
          echo "Fetching resources for $STS_NAME in namespace $NAMESPACE..."
          kubectl get statefulset $STS_NAME --namespace $NAMESPACE -o json | jq '.spec.template.spec.containers[] | {resources}' > /tmp/output/resources_$NAMESPACE.json
        fi
      }
      fetch_resource_data
  tags:
    - cache-utility-test
    - tp2-edco-cache-test-b
    - tp2-edco-cache-test-c

# Consolidate results from EDCR and EDCO
consolidate_report:
  stage: consolidate
  needs: ["fetch_resources_edcr", "fetch_resources_edco"]
  script:
    - echo "Consolidating all resource details..."
    - jq -s 'reduce .[] as $item ({}; . * $item)' /tmp/output/resources_*.json > /tmp/output/final_report.json
    - cat /tmp/output/final_report.json  # Display the final report
  artifacts:
    paths:
      - /tmp/output/final_report.json
  tags:
    - cache-utility-edcr
    - cache-utility-test





















new
stages:
  - ping-instances
  - consolidate-results

ping_cache_prod:
  stage: ping-instances
  image: $KUBECTL  # Use the KUBECTL image for kubectl commands
  script:
    - echo "Fetching pod names and IPs for cache-prod namespace"
    - kubectl get pods -n cache-prod -o custom-columns=POD:.metadata.name,IP:.status.podIP --no-headers > pod_ips_cache_prod.txt
    - echo "Pod names and IPs for cache-prod:"
    - cat pod_ips_cache_prod.txt
    - echo "Switching to nester pod for ping operations"
    - kubectl exec -n nester-namespace nester-pod -- sh -c "
        touch PING_RESULTS_CACHE_PROD.txt
        while read -r pod ip; do
          DNS_NAME=\$pod.cache-prod;
          echo 'Pinging pod \$DNS_NAME (\$ip) in cache-prod namespace';
          PING=\$(timeout 5 sh -c '(echo ping; sleep 1) | nc -q 1 -v \$ip 6379 2>&1');
          echo 'Full output for \$DNS_NAME: \$PING';
          if [ \$? -eq 124 ]; then
            echo '\$DNS_NAME.cache-prod STS is Down' >> PING_RESULTS_CACHE_PROD.txt;
          elif echo '\$PING' | grep -q '+PONG'; then
            echo '\$DNS_NAME.cache-prod +PONG' >> PING_RESULTS_CACHE_PROD.txt;
          else
            echo '\$DNS_NAME.cache-prod Connection failed: \$PING' >> PING_RESULTS_CACHE_PROD.txt;
          fi
        done < pod_ips_cache_prod.txt
      "
  tags:
    - cache-utility-edcr
  artifacts:
    paths:
      - PING_RESULTS_CACHE_PROD.txt

ping_tp2_cache_prod_a:
  stage: ping-instances
  image: $KUBECTL  # Use the KUBECTL image for kubectl commands
  script:
    - echo "Fetching pod names and IPs for tp2-cache-prod-a namespace"
    - kubectl get pods -n tp2-cache-prod-a -o custom-columns=POD:.metadata.name,IP:.status.podIP --no-headers > pod_ips_tp2_cache_prod_a.txt
    - echo "Pod names and IPs for tp2-cache-prod-a:"
    - cat pod_ips_tp2_cache_prod_a.txt
    - echo "Switching to nester pod for ping operations"
    - kubectl exec -n nester-namespace nester-pod -- sh -c "
        touch PING_RESULTS_TP2_CACHE_PROD_A.txt
        while read -r pod ip; do
          DNS_NAME=\$pod.tp2-cache-prod-a;
          echo 'Pinging pod \$DNS_NAME (\$ip) in tp2-cache-prod-a namespace';
          PING=\$(timeout 5 sh -c '(echo ping; sleep 1) | nc -q 1 -v \$ip 6379 2>&1');
          echo 'Full output for \$DNS_NAME: \$PING';
          if [ \$? -eq 124 ]; then
            echo '\$DNS_NAME.tp2-cache-prod-a STS is Down' >> PING_RESULTS_TP2_CACHE_PROD_A.txt;
          elif echo '\$PING' | grep -q '+PONG'; then
            echo '\$DNS_NAME.tp2-cache-prod-a +PONG' >> PING_RESULTS_TP2_CACHE_PROD_A.txt;
          else
            echo '\$DNS_NAME.tp2-cache-prod-a Connection failed: \$PING' >> PING_RESULTS_TP2_CACHE_PROD_A.txt;
          fi
        done < pod_ips_tp2_cache_prod_a.txt
      "
  tags:
    - tp2-edcr-prod-a
  artifacts:
    paths:
      - PING_RESULTS_TP2_CACHE_PROD_A.txt

ping_tp2_cache_prod_b:
  stage: ping-instances
  image: $KUBECTL  # Use the KUBECTL image for kubectl commands
  script:
    - echo "Fetching pod names and IPs for tp2-cache-prod-b namespace"
    - kubectl get pods -n tp2-cache-prod-b -o custom-columns=POD:.metadata.name,IP:.status.podIP --no-headers > pod_ips_tp2_cache_prod_b.txt
    - echo "Pod names and IPs for tp2-cache-prod-b:"
    - cat pod_ips_tp2_cache_prod_b.txt
    - echo "Switching to nester pod for ping operations"
    - kubectl exec -n nester-namespace nester-pod -- sh -c "
        touch PING_RESULTS_TP2_CACHE_PROD_B.txt
        while read -r pod ip; do
          DNS_NAME=\$pod.tp2-cache-prod-b;
          echo 'Pinging pod \$DNS_NAME (\$ip) in tp2-cache-prod-b namespace';
          PING=\$(timeout 5 sh -c '(echo ping; sleep 1) | nc -q 1 -v \$ip 6379 2>&1');
          echo 'Full output for \$DNS_NAME: \$PING';
          if [ \$? -eq 124 ]; then
            echo '\$DNS_NAME.tp2-cache-prod-b STS is Down' >> PING_RESULTS_TP2_CACHE_PROD_B.txt;
          elif echo '\$PING' | grep -q '+PONG'; then
            echo '\$DNS_NAME.tp2-cache-prod-b +PONG' >> PING_RESULTS_TP2_CACHE_PROD_B.txt;
          else
            echo '\$DNS_NAME.tp2-cache-prod-b Connection failed: \$PING' >> PING_RESULTS_TP2_CACHE_PROD_B.txt;
          fi
        done < pod_ips_tp2_cache_prod_b.txt
      "
  tags:
    - tp2-edcr-prod-b
  artifacts:
    paths:
      - PING_RESULTS_TP2_CACHE_PROD_B.txt

# Consolidate all results into a single file
consolidate_results:
  stage: consolidate-results
  script:
    - touch ALL_PING_RESULTS.txt
    - for file in PING_RESULTS_*.txt; do
        cat $file >> ALL_PING_RESULTS.txt
      done
  artifacts:
    paths:
      - ALL_PING_RESULTS.txt
  when: always
